### ISSUE TITLE
rename blacklist feature

### ISSUE THREAD

**Issue by JR-git-hub** [Balastrong/trello-card-numbers-plus#21]
Please rename the blacklist feature to blocklist or similar.

**Comment by Balastrong** [comment]
`blocklist` seems confusing, but I get the point... what do you think about `excludedBoards`?

After all, it will contain a list of boards that are excluded by the functionality. Let me know what you think!

**Comment by JR-git-hub** [comment]
Sounds good to me. Very clear. Thanks.

**Comment by Balastrong** [comment]
That's great!

Would you like to take care of that and open a PR?
