### ISSUE TITLE
Numbers do not appear unless configs are saved at least once from the popup

### ISSUE THREAD

**Issue by ambujsahu81** [Balastrong/trello-card-numbers-plus#25]
**Describe the bug**
Currently number in trello cards are not appearing. 
It works fine when we enter some input in the Excluded boards field.

**Trello Card Numbers Plus version**
1.10

**Comment by Balastrong** [comment]
Thank you for the report!

At first look, there must be something wrong when the `excludedBoards` config is either empty or `undefined`. Do you want to give it a try and open a PR?

Probably this function, or where it is used:
https://github.com/Balastrong/trello-card-numbers-plus/blob/02cb896b174b8559521e0a289f301a906ff6a814/src/shared/utils.ts#L35-L38

Let me know if you want to take this up, otherwise I'll have a look myself in the evening :)

**Comment by ambujsahu81** [comment]
Hi Leonardo Montini

I gave it a good try but I couldn't find the problem.
 It is working when we refresh the page but it lags when we press
excludedBoards-toggle-btn for the first time there after even clicking on
the save config it doesn't update the preview. I think it is better if you
will fix it. But thanks for opportunity. 🙂

**Comment by Balastrong** [comment]
I have to say I can't find the reason either. My first guess was wrong, no errors are logged so probably it's not the `excludedBoard` update.

In local, as soon as I load the extension and open a Trello board it just works. However, when I install it from the Chrome store, numbers appear only if I manually open the popup and click Save.

I'm open to suggestions :D

**Comment by ambujsahu81** [comment]
Even when we switch boards cards number disappears. Need to reload the page to see card numbers again.

 

https://user-images.githubusercontent.com/118078892/206838199-d7216440-e2aa-4aff-8b77-0ea1cac7baf1.mp4

It may be due to the **load event** used here -

https://github.com/Balastrong/trello-card-numbers-plus/blob/02cb896b174b8559521e0a289f301a906ff6a814/src/trelloCardNumberPlus.ts#L23-L28

**Comment by Balastrong** [comment]
Thanks, I never tried switching boards actually and indeed it doesn't work properly 😅

I'm attempting a fix with #27 and I'll submit a new version today. It usually takes one or two days before the version is distributed, I'll let you know!

**Comment by Balastrong** [comment]
It _usually_ takes a day or two, but this time they approved it in less than 20 minutes 🚀 

@ambujsahu81 can you please give it a try now and see if something has changed?

**Comment by ambujsahu81** [comment]
yes now card numbers are visible and it is  working even while switching boards. :smiley:
Thanks for fixing it

**Comment by Balastrong** [comment]
Thank you for raising the issue! ❤️
