### ISSUE TITLE
The card numbers are duplicated when I click on any card.

### ISSUE THREAD

**Issue by dinterlandi-soulit** [Balastrong/trello-card-numbers-plus#30]
![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/57414825/22823b5b-4848-41df-8ce0-8b19dab391af)

![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/57414825/d087078e-c6b5-4f74-bcd7-ecca9aa42622)

![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/57414825/fb16f506-e942-40e7-8888-6089989fafa2)

**Comment by Balastrong** [comment]
Hey @dinterlandi-soulit, yeah you're right!

I change a little thing to fix the other bug (numbers disappeared when trello changed some html on their side) but now numbers are added each time.

I'll try to clean up the code later today or if you want to give it a try let me know, I'll be happy to accept a PR :)

**Comment by Balastrong** [comment]
I pushed the new extension on the store, it usually gets approved within 24 hours :)

**Comment by dinterlandi-soulit** [comment]
Thank you very much!!! 🙌🙌🙌
