### ISSUE TITLE
Color picker not visibile

### ISSUE THREAD

**Issue by jbruchanov** [Balastrong/trello-card-numbers-plus#31]
Version:1.2.0
OS: Windows 11
browser: Chrome Version 118.0.5993.89 (Official Build) (64-bit)

![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/1651939/82edcec3-ca3a-4561-9504-ce3af69d4a63)

**Comment by Balastrong** [comment]
Hey @jbruchanov, thank you for the report!

I had to remove it to quickly fix the other bug (numbers disappeared when trello changed some html on their side). I'll try to restore it as soon as possible.

Let me know if you want to work on it, or I'll try to give it a look later :)

**Comment by jbruchanov** [comment]
> Hey @jbruchanov, thank you for the report!
> 
> I had to remove it to quickly fix the other bug (numbers disappeared when trello changed some html on their side). I'll try to restore it as soon as possible.
> 
> Let me know if you want to work on it, or I'll try to give it a look later :)

Thanks for super quick response.
I'm not experienced with dev of chrome extension nor web, so probably the setup would take me more time than for you :).
Anyway it's rather minor, slightly hard to read having some "dark" theme.

![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/1651939/cf4d54f3-3677-4e80-867c-4446e76d36e1)

Anyway if you could fix the other one 
https://github.com/Balastrong/trello-card-numbers-plus/issues/30
that's more annoying..

thanks  a lot 
btw awesome extension🥇, 
I still don't get it why trello guys don't have it by default, so many comments/plugins to deal with this annoying UX.
