### ISSUE TITLE
Rewrite core logic after Trello html changes

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/trello-card-numbers-plus#32]
It seems like Trello changed something in their markup and entirely removed the hidden element with the number.

Numbers are still easy to grab but the element is no longer there and some classes have been changed, breaking the some functionalities of the extension, including:
- [x] Card counters
- [x] Number on new cards
- [x] Number on moved cards
- [x] Number on renamed cards
- [x] Toggle between show/hide numbers

**Comment by raphaeluncp** [comment]
No aguardo de uma correção!
