### ISSUE TITLE
Card number displayed is always '10 cards'

### ISSUE THREAD

**Issue by jerome-raffalli** [Balastrong/trello-card-numbers-plus#35]
Hello,

**Describe the bug**
Card number is wrong, always 10

**Screenshots**
![image](https://github.com/Balastrong/trello-card-numbers-plus/assets/22653911/31e0d44d-3167-49ad-be4e-1012acac11b2)

**Trello Card Numbers Plus version**

**Comment by Balastrong** [comment]
Should be fixed in the new version, I'm pushing it now to the chrome store :)
